Fix broken links
I found there were a bunch of broken links, due to refactoring in the pact-jvm project.  So I ran a link checker to find them all.

Here is a report of the broken links, which are all now fixed:

```
➜  pact-sample git:(master) markdown-link-check README.md                                                                                                0s

FILE: README.md
[✓] https://github.com/DiUS/pact-jvm
[✓] https://martinfowler.com/articles/consumerDrivenContracts.html
[✖] https://github.com/DiUS/pact-jvm/tree/master/pact-jvm-consumer-groovy
[✖] https://github.com/DiUS/pact-jvm/tree/master/pact-jvm-provider-junit
[✖] https://github.com/DiUS/pact-jvm/tree/master/pact-jvm-consumer-groovy#publishing-your-pact-files-to-a-pact-broker
[✖] https://github.com/DiUS/pact-jvm/tree/master/pact-jvm-provider-junit#download-pacts-from-a-pact-broker
[✓] https://github.com/DiUS/pact-jvm#i-am-writing-a-provider-and-want-to-
[✓] https://github.com/realestate-com-au/pact-jvm-provider-spring-mvc
[✖] https://github.com/DiUS/pact-jvm/tree/master/pact-jvm-provider-gradle
[✓] https://github.com/johnrengelman/gradle-processes
[✖] https://github.com/DiUS/pact-jvm/tree/master/pact-jvm-provider-gradle#publishing-pact-files-to-a-pact-broker-version-227
[✓] http://www.chuanchuanlaw.com/pact-how-to-write-consumer-test/
[✓] http://www.chuanchuanlaw.com/pact-how-to-write-provider-test/
[✖] http://dius.com.au/2016/02/03/microservices-pact/
[✓] https://github.com/mstine/microservices-pact
[✓] https://github.com/DiUS/pact-workshop-jvm

ERROR: dead links found!

```